ajuste

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -71,6 +71,27 @@ jobs:
       - name: Copy private key to temporaria/target
         run: cp private_ec2_key.pem temporaria/target/
 
+      # Add Bastion Host and Private EC2 to known_hosts
+      - name: Add Bastion and Private EC2 Hosts to known_hosts
+        run: |
+          mkdir -p ~/.ssh
+          chmod 700 ~/.ssh
+          echo "Adding Bastion Host and Private EC2 Host to known_hosts..."
+          
+          # Add Bastion Host to known_hosts
+          ssh-keyscan -H ${{ secrets.PUBLIC_EC2_HOST }} >> ~/.ssh/known_hosts || {
+            echo "Failed to add Bastion host to known_hosts. Exiting...";
+            exit 1;
+          }
+
+          # Add Private EC2 Host to known_hosts
+          ssh-keyscan -H ${{ secrets.PRIVATE_EC2_HOST }} >> ~/.ssh/known_hosts || {
+            echo "Failed to add Private EC2 host to known_hosts. Exiting...";
+            exit 1;
+          }
+
+          chmod 644 ~/.ssh/known_hosts
+
       # Test SSH Connectivity through Bastion Host with -J (ProxyJump)
       - name: Test SSH Connectivity through Bastion
         run: |
@@ -79,17 +100,6 @@ jobs:
             echo "SSH connection failed!";
             exit 1;
           }
-
-      - name: Add Private EC2 Host to known_hosts
-        run: |
-          mkdir -p ~/.ssh
-          chmod 700 ~/.ssh
-          echo "Adding Private EC2 Host to known_hosts..."
-          ssh-keyscan -H ${{ secrets.PRIVATE_EC2_HOST }} >> ~/.ssh/known_hosts || {
-            echo "Failed to add host to known_hosts. Exiting...";
-            exit 1;
-          }
-          chmod 644 ~/.ssh/known_hosts
 
       - name: Transfer JAR to Public EC2
         uses: appleboy/scp-action@v0.1.6
